variables:
  APP_DIR: "/var/www/html"
  MODULE_NAME: "itime"
  APP_NAME: "webapp"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build_localhost:
  stage: build
  before_script:
    - 'npm install'
  script:
    - ng build --prod  --base-href /$MODULE_NAME/$APP_NAME/  --deploy-url /$MODULE_NAME/$APP_NAME/ --aot --build-optimizer --extract-css --extract-licenses --vendor-chunk=true --i18n-locale id --stats-json
  artifacts:
    paths:
      - dist/*
  only:
    - /-release$/

deploy_localhost:
  stage: deploy
  script:
    - 'rm -rf $APP_DIR/$MODULE_NAME/*'
    - 'cp -r dist/* $APP_DIR/'
  only:
    - /-release$/
